app/models.py
from app import db,login_manager
from flask_login import UserMixin,current_user
from werkzeug.security import generate_password_hash,check_password_hash
from sqlalchemy.orm import joinedload
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

class Business(db.Model):
    __tablename__='businesses'
    id=db.Column(db.Integer,primary_key=True)
    business_name=db.Column(db.String(255))
    description=db.Column(db.Text())
    businesses=db.relationship('Reviews',backref='businesses')
    userid=db.Column(db.Integer,db.ForeignKey('users.id'))

    def all_busn(self):
        db.query.options(joinedload('business_name'))

    def del_busn(self):
        db.session.delete(self)
        db.session.commit()


class User(UserMixin,db.Model):
    __tablename__='users'
    id=db.Column(db.Integer,primary_key=True)
    username=db.Column(db.String(255),index=True,unique=True)
    email=db.Column(db.String(255),unique=True,index=True)
    phone_number=db.Column(db.Integer)
    passwd=db.Column(db.String(255))
    reviews=db.relationship('Reviews',backref='users')
    businesses=db.relationship('Business',backref='users')
    @property
    def password(self):
        raise AttributeError('You cannot the password attribute')
    @password.setter
    def password(self,password):
        self.passwd=generate_password_hash(password)
    def verify_password(self,password):
        return check_password_hash(self.passwd,password)

class Reviews(db.Model):
    __tablename__='reviews'
    id=db.Column(db.Integer,primary_key=True)
    review=db.Column(db.Text,nullable=False)
    businessesid=db.Column(db.Integer,db.ForeignKey('businesses.id'))
    userid=db.Column(db.Integer,db.ForeignKey('users.id'))
    review_date =db.Column(db.DateTime, nullable=False,
        default=datetime.utcnow)

    def add_review(self):
        db.session.add(self)
        db.session.commit()

class Catalogue(db.Model):
    __tablename__='catalogues'
    id=db.Column(db.Integer,primary_key=True)
    picture_path=db.Column(db.String())

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,PasswordField,SubmitField,BooleanField,IntegerField,TextField
from wtforms.validators import DataRequired,Length,Email,EqualTo


class BusinessRegistrationForm(FlaskForm):
    name=StringField('Business Name',validators=[DataRequired(),Length(min=5,max=50)])
    description=StringField('Business Description',validators=[DataRequired()])
    owner=StringField('Owner',validators=[DataRequired()])
    submit=SubmitField('Register')


class ReviewForm(FlaskForm):
    review=TextField('Business Review',validators=[DataRequired(),Length(min=5,max=500)])
    

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from config import config_options

bootstrap=Bootstrap()
db=SQLAlchemy()
login_manager=LoginManager()
photos=UploadSet('photos',IMAGES)
login_manager.session_protection='strong'

def create_app(config_name):
    '''
    Function that takes configuration setting key as an argument
    Args:
        config_name:name of the configuartion to be used
    '''
    # initialize the application
    app=Flask(__name__)

    # app configurations
    app.config.from_object(config_options[config_name])
    configure_uploads(app,photos)

    # initialize flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    # registering the main blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    # registering the auth blueprint
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix='/auth')

    return app

app/main/__init__.py
from flask import Blueprint
main=Blueprint('main',__name__)
from . import views

app/main/views.py
from flask import current_app as app
from app import db
from flask import render_template,redirect,url_for,flash,request
from . import main
from ..models import Business,User,Catalogue,Reviews
from .forms import BusinessRegistrationForm,ReviewForm
from flask_login import login_required,current_user,login_user,logout_user


@main.route('/',methods=['GET','POST'])
def index():
    return render_template('index.html')

@main.route('/register/businesses',methods=['GET','POST'])
@login_required
def reg_busn():
    form=BusinessRegistrationForm()
    if form.validate_on_submit():
        name=form.name.data
        description=form.description.data
        owner=current_user.id
        test_busn=Business(business_name=name,description=description,userid=owner)
        db.session.add(test_busn)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('biz_registration.html',form=form)

@main.route('/edit/businesses/<string:busn_name>',methods=['GET','POST'])
@login_required
def update_busn(busn_name):
    if request.method == 'POST':
        form=BusinessRegistrationForm()
        newdesc = form.description.data
        test_busn=Business.query.filter_by(business_name=busn_name).first_or_404()
        if test_busn.userid==current_user.id:
            test_busn.description=newdesc
            db.session.commit()
            return render_template('biz_registration.html',form=form)

    else:
        form=BusinessRegistrationForm()
        return render_template('biz_registration.html',form=form)


@main.route('/delete/businesses/<string:busn_name>',methods=['GET','POST'])
def delete_busn(busn_name):
    test_busn=Business.query.filter_by(business_name=busn_name).first_or_404()
    if not test_busn==[]:
        if test_busn.userid==current_user.id:
            db.session.delete(test_busn)
            db.session.commit()
            return ('hey')
        else:
            return ('not yours')
    return ('not found')

@main.route('/businesses/all',methods=['GET','POST'])
def post_all_busn():
    business=Business.query.all()
    businesses=[]
    for business in business:
        businesses.append(business.business_name)
    return render_template('show_all.html',businesses=businesses)

@main.route('/businesses/catalog/all',methods=['GET','POST'])
def get_all_catalog():
    pass

@main.route('/category/<string:cat_name>',methods=['GET','POST'])
def get_categories():
    category=Category.query.filter(name=cat_name).first_or_404()
    businesses=category.businesses.query.all()
    return render_template('catergory.html',category=category,businesses=businesses)


@main.route('/businesses/reviews/<string:busn_name>', methods=['GET','POST'])
def reviews(busn_name):
    form=ReviewForm()
    reviewer=current_user.id
    review=form.review.data
    test_busn=Reviews(review=review)
    db.session.add(test_busn)
    db.session.commit()
    return render_template('reviews.html',form=form)

app/templates/biz_registration.html
{% import  'bootstrap/wtf.html' as wtf%}
{% extends 'index.html'%}
{%block content%}
         {{wtf.quick_form(form)}}
        <hr>
     <div class="border-top pt-3">
      <small class="text-muted">
        Already have a business ? <a class="ml-2" href="#">visit </a>
      </small>
     </div>
{%endblock%}

app/templates/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{{title}}-App</title>
    <link rel="stylesheet" href="{{url_for('static',filename='styles.css')}}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  </head>
  <body class="bodyground">
    <div class="container">
      {% block content %}
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
<a class="navbar-brand" href="#">Navbar</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarNav">
  <ul class="navbar-nav">
    {% if current_user.is_authenticated %}
    <li class="nav-item active">
      <a class="nav-link" href="{{url_for('main.index')}}">Home <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{{url_for('main.reg_busn')}}">Add Your Business</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{{url_for('main.post_all_busn')}}">View Business</a>
    </li>
    <li class="nav-item">
      <a class="nav-link disabled" href="{{url_for('auth.logout')}}">Logout</a>
    </li>
    {% else %}
    <li class="nav-item">
      <a class="nav-link disabled" href="{{url_for('auth.register')}}">Sign Up</a>
    </li>
    <li class="nav-item">
      <a class="nav-link disabled" href="{{url_for('auth.login')}}">Login</a>
    </li>
    {% endif %}

  </ul>
</div>
</nav>
      <h1>WELCOME! TO BIZNAPAP!</h1>
      <p>  Register Your Business Here!</p>
        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </body>

</html>

app/templates/login.html
{% import  'bootstrap/wtf.html' as wtf%}
{% extends 'index.html'%}
{% block content%}
    {{wtf.quick_form(form)}}
{%endblock%}

app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
  </div>
</nav>

app/templates/registration.html
{% import  'bootstrap/wtf.html' as wtf%}
{% extends 'index.html'%}
{%block content%}
         {{wtf.quick_form(form)}}
        <hr>
     <div class="border-top pt-3">
      <small class="text-muted">
        Already have an account? <a class="ml-2" href="{{url_for('auth.login')}}">sign in </a>
      </small>
     </div>
{%endblock%}

app/templates/reviews.html
{% import  'bootstrap/wtf.html' as wtf%}
{% extends 'index.html'%}
{% block content%}
    {{wtf.quick_form(form)}}
{%endblock%}

app/templates/show_all.html
{% import  'bootstrap/wtf.html' as wtf%}
{% extends 'index.html'%}
{% block content%}
<ul>
  {% for busn in businesses%}
  <li>
        {{busn}}
        <a class="nav-link" href="{{url_for('main.delete_busn', busn_name=busn)}}">Delete Your Business</a>
</li>
    {%endfor%}
{%endblock%}
</ul>